name: webphonon  # the name of the snap
version: 2.0  # the version of the snap
summary: Simple Qt based Media Player  # 79 char long summary
description: WebPhonon is a Qt based meida player and library manager  # a longer description for the snap
confinement: devmode  # use "strict" to enforce system access only via declared interfaces
apps:
     webphonon:
             command: qt5-launch WebPhonon-Qt5

parts:
#     libphonon:
#        plugin: cmake
#        source: git://anongit.kde.org/phonon.git
#     phonon-backend:
#       plugin: cmake
#        source: git://anongit.kde.org/phonon-gstreamer.git

     webphonon:
        plugin: cmake
        source: https://github.com/Zakhrov/WebPhonon-Qt5.git
        build-packages: [qt5-default, qtbase5-dev, libphonon4qt5-dev, libqt5opengl5-dev, extra-cmake-modules, libphonon4qt5experimental-dev, libqt5x11extras5-dev]
        stage-packages: [libqt5gui5, libqt5widgets5, libphonon4qt5-4, libqt5opengl5, libphonon4qt5experimental, libqt5x11extras5]
        after: [qt5conf]
         
